### ISSUE TITLE
Добавить тоггл для включения постоянного префикса коммита

### ISSUE THREAD

**Issue by PrepConcedeITIS** [azatyamanaev/git-commit-template#1]
Идея такая:
Реализовать галочку, активирующую постоянный префикс задачи над которой ведется работа, исходя из названия ветки. При этом остается возможность дополнить название коммита по стандартному сценарию, описанному в https://github.com/azatyamanaev/git-commit-template/blob/main/usage/USAGE.md.

**Comment by azatyamanaev** [comment]
Этот префикс будет добавляться к переменной task?

**Comment by azatyamanaev** [comment]
Этот префикс будет работать отдельно от переменных, которые можно вставлять в шаблоны? Просто сейчас в шаблонах уже есть пример с вставкой задачи через переменную

**Comment by azatyamanaev** [comment]
Может получиться дублирование данных. Но я думаю это не критично и можно оставить на усмотрение пользователей

**Comment by azatyamanaev** [comment]
Есть предложение: если добавляется префикс на основании ветки гита, можно сделать выбор - префикс задачи или префикс ветки. Ветка не всегда отвечает за одну задачу

**Comment by azatyamanaev** [comment]
Добавление в целом полезное, потому что пока у плагина нет интеграции с гитом
