### ISSUE TITLE
Возможность использовать переменные без префикса 'GITT_'

### ISSUE THREAD

**Issue by maestro-game** [azatyamanaev/git-commit-template#4]
Иногда хочется отображать в коммите некую системную переменную (тот же JAVA_HOME), что в текущей реализации сделать невозможно, но я могу это реализовать.

Предлагаю для системных переменных такой синтаксис: `$$VALUE_NAME`.

Например `$$JAVA_HOME` замениться на `JAVA_HOME - C:\Program Files\Java\jdk-21`

Так же по пути могу добавить хоткей для вызова меню вставки шаблона коммита и сделать навигацию клавишами в списке шаблонов (выбор + подтверждение)

**Comment by azatyamanaev** [comment]
По поводу хоткея и навигации клавишами нет возражений. Только если добавлять хоткей, надо будет сделать возможность его изменять в настройках к плагину

**Comment by azatyamanaev** [comment]
Системные переменные могут быть использованы в шаблонах без префикса. Если создать переменную GITT_JAVA_HOME, то в шаблоне ее можно будет использовать через $&JAVA_HOME

**Comment by maestro-game** [comment]
> Системные переменные могут быть использованы в шаблонах без префикса. Если создать переменную GITT_JAVA_HOME, то в шаблоне ее можно будет использовать через $&JAVA_HOME

Это понятно, но если при существующей реализации, переменная JAVA_HOME (обычная, без префикса) измениться (например поставил новую версию java или просто переключил на другую версию), то переменная GITT_JAVA_HOME не измениться пока её руками не отредачат

**Comment by azatyamanaev** [comment]
Использовать переменные напрямую будет удобнее, с этим согласен.
Метод для получения всех системных переменных уже есть. К нему можно добавить возможность выбирать какие переменные будут доступны для использования через, например, какой-нибудь список с чекбоксами в настройках

**Comment by maestro-game** [comment]
А зачем выбирать доступные переменные чекбоксами? Может лучше оставить доступными все переменные?

**Comment by azatyamanaev** [comment]
Пользователи точно не будут использовать все возможные переменные окружения. Если будет возможность скрывать переменные из списка, этим будет легче пользоваться

**Comment by maestro-game** [comment]
Дык мы ж не скрываем из списка. Список в любом случае будет из всех переменных окружения с чекбоксами. Просто, как я понял, если пользователь напишет `$$JAVA_HOME`, то она будет заменяться только в том случае, когда у этой переменной включен чекбокс. Но если пользователь уже написал `$$JAVA_HOME` не означает ли это, что он в любом случае хочет её использовать и чекбокс в этом процессе лишний?

**Comment by azatyamanaev** [comment]
В настройках должен быть список доступных переменных окружения. Пользователь должен знать какие переменные он может использовать. Он же не будет каждый раз в настройки системы лезть. 

При этом явно не каждому пользователю будут нужны все возможные переменные окружения. Поэтому было бы неплохо иметь возможность оставить в этом списке только те переменные, которые часто используются, чтобы не пролистывать каждый раз весь список. И допустим добавить какую-нибудь кнопку для возвращения всех скрытых переменных.

**Comment by maestro-game** [comment]
Окей, пусть будет так. Добавляю вкладку с системными переменными. В ней отображаются выбранные переменные и кнопка добавления в список системной переменной

**Comment by azatyamanaev** [comment]
> Окей, пусть будет так. Добавляю вкладку с системными переменными. В ней отображаются выбранные переменные и кнопка добавления в список системной переменной

Вкладка с системными переменными уже есть

**Comment by maestro-game** [comment]
Это же вкладка для переменных GITT_..., но да, могу её переделать

**Comment by maestro-game** [comment]
В принципе, если реализовать оговоренный функционал, то он функционально покрывает префикс `GITT_`, ибо можно будет добавлять любую переменную среды. Возможно стоит выпилить функционал работы с `GITT_`

**Comment by azatyamanaev** [comment]
да

**Comment by maestro-game** [comment]
Этот PR закрывает данное issue. Дублирую сюда:
- Добавлена навигация с помощью клавиатуры по меню выбора шаблона
- Добавлен функционал выбора системных переменных
- Добавлен хоткей для вызова меню выбора шаблона
- Небольшие улучшения кода
